## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import keras_tuner as kt

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_count = application_df['APPLICATION_TYPE'].value_counts()
application_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_count[application_count < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count[classification_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_count[classification_count < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
X = dummies_df.drop('IS_SUCCESSFUL', axis=1)
y = dummies_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()
input_dim = len(X.columns)

# First hidden layer
nn.add(tf.keras.layers.Dense(units=120, activation="relu", input_dim=input_dim))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 120)            │         5,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 80)             │         9,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,421 (68.05 KB)

 Trainable params: 17,421 (68.05 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 443us/step - accuracy: 0.7174 - loss: 0.5778
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7297 - loss: 0.5576
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7328 - loss: 0.5523
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7339 - loss: 0.5477
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.7311 - loss: 0.5521
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.7353 - loss: 0.5459
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7354 - loss: 0.5471
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7322 - loss: 0.5491
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7284 - loss: 0.5524
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.7329 - loss: 0.5466
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.7306 - loss: 0.5488
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7337 - loss: 0.5433
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7385 - loss: 0.5344
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7343 - loss: 0.5441
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7350 - loss: 0.5431
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7339 - loss: 0.5455
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7384 - loss: 0.5377
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7370 - loss: 0.5388
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7368 - loss: 0.5400
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7370 - loss: 0.5404
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7392 - loss: 0.5385
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7412 - loss: 0.5390
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7361 - loss: 0.5416
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.7411 - loss: 0.5342
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7384 - loss: 0.5390
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7344 - loss: 0.5427
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7393 - loss: 0.5377
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7382 - loss: 0.5379
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7374 - loss: 0.5397
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.7335 - loss: 0.5424
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7406 - loss: 0.5345
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7380 - loss: 0.5375
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7434 - loss: 0.5320
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7381 - loss: 0.5350
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7368 - loss: 0.5361
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7404 - loss: 0.5352
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7386 - loss: 0.5405
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.7410 - loss: 0.5315
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.7372 - loss: 0.5369
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.7406 - loss: 0.5338
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.7353 - loss: 0.5384
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7398 - loss: 0.5368
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.7443 - loss: 0.5295
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.7366 - loss: 0.5390
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.7380 - loss: 0.5370
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.7423 - loss: 0.5333
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7377 - loss: 0.5401
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7365 - loss: 0.5395
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7388 - loss: 0.5335
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7403 - loss: 0.5314
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.7350 - loss: 0.5355
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7375 - loss: 0.5377
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7404 - loss: 0.5316
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7370 - loss: 0.5365
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7433 - loss: 0.5282
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7443 - loss: 0.5281
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7393 - loss: 0.5340
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7396 - loss: 0.5366
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7389 - loss: 0.5318
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7432 - loss: 0.5313
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7386 - loss: 0.5377
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7379 - loss: 0.5354
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7369 - loss: 0.5379
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7416 - loss: 0.5303
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7426 - loss: 0.5309
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7405 - loss: 0.5335
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.7451 - loss: 0.5290
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7389 - loss: 0.5311
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7428 - loss: 0.5296
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.7382 - loss: 0.5380
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - accuracy: 0.7392 - loss: 0.5330
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7393 - loss: 0.5332
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7441 - loss: 0.5270
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7434 - loss: 0.5302
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.7406 - loss: 0.5319
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7397 - loss: 0.5333
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7418 - loss: 0.5324
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7366 - loss: 0.5375
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7436 - loss: 0.5307
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.7416 - loss: 0.5350
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7421 - loss: 0.5302
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7430 - loss: 0.5295
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7395 - loss: 0.5341
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.7364 - loss: 0.5362
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.7427 - loss: 0.5304
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.7419 - loss: 0.5329
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7414 - loss: 0.5334
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7371 - loss: 0.5356
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.7419 - loss: 0.5302
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.7360 - loss: 0.5366
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.7416 - loss: 0.5327
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.7406 - loss: 0.5315
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7373 - loss: 0.5354
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7431 - loss: 0.5301
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7347 - loss: 0.5372
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.7387 - loss: 0.5344
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7395 - loss: 0.5350
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7398 - loss: 0.5326
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7427 - loss: 0.5276
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7444 - loss: 0.5263

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 481us/step - accuracy: 0.7303 - loss: 0.5854
Loss: 0.5854024291038513, Accuracy: 0.7302623987197876

In [16]:
# Export our model to the native Keras format as HDF5 file format is considered to be legacy
nn.save('Output/AlphabetSoupCharity_Optimization.keras')

# Use Keras Tuner for hyperparameter tuning to create and test different model architectures

In [30]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu', 'tanh', 'leaky_relu', 'sigmoid'])

    # Set input to match the dataset
    input_dim = len(X.columns)

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=30,
        step=5), activation=activation, input_dim=input_dim))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=30,
            step=5),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

    # Compile the model
    nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    return nn_model

In [31]:
# Initialize Hyperband tuner
tuner = kt.Hyperband(
    create_model,
    objective='val_accuracy',
    max_epochs=20,
    hyperband_iterations=2,
    overwrite=True
)

# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 58 Complete [00h 00m 10s]
val_accuracy: 0.7318950295448303

Best val_accuracy So Far: 0.7318950295448303
Total elapsed time: 00h 05m 06s

In [32]:
# Get top 3 model hyperparameters and print the values
top_hyper = tuner.get_best_hyperparameters(3)
for param in top_hyper:
    print(param.values)

{'activation': 'relu', 'first_units': 26, 'num_layers': 1, 'units_0': 16, 'units_1': 26, 'units_2': 6, 'units_3': 21, 'units_4': 6, 'tuner/epochs': 20, 'tuner/initial_epoch': 0, 'tuner/bracket': 0, 'tuner/round': 0}
{'activation': 'relu', 'first_units': 26, 'num_layers': 4, 'units_0': 21, 'units_1': 26, 'units_2': 26, 'units_3': 21, 'units_4': 6, 'tuner/epochs': 20, 'tuner/initial_epoch': 7, 'tuner/bracket': 2, 'tuner/round': 2, 'tuner/trial_id': '0015'}
{'activation': 'leaky_relu', 'first_units': 6, 'num_layers': 4, 'units_0': 21, 'units_1': 16, 'units_2': 11, 'units_3': 11, 'units_4': 16, 'tuner/epochs': 20, 'tuner/initial_epoch': 0, 'tuner/bracket': 0, 'tuner/round': 0}

In [33]:
# Evaluate the top 3 models against the test dataset
top_model = tuner.get_best_models(3)
for model in top_model:
    model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
    print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 587us/step - accuracy: 0.7319 - loss: 0.5563
Loss: 0.5563399195671082, Accuracy: 0.7318950295448303
268/268 - 0s - 616us/step - accuracy: 0.7317 - loss: 0.5553
Loss: 0.555250346660614, Accuracy: 0.7316617965698242
268/268 - 0s - 762us/step - accuracy: 0.7312 - loss: 0.5561
Loss: 0.5560919046401978, Accuracy: 0.731195330619812

In [34]:
# Get second best model hyperparameters
second_hyper = tuner.get_best_hyperparameters(2)[1]
second_hyper.values

{'activation': 'relu',
 'first_units': 26,
 'num_layers': 4,
 'units_0': 21,
 'units_1': 26,
 'units_2': 26,
 'units_3': 21,
 'units_4': 6,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 7,
 'tuner/bracket': 2,
 'tuner/round': 2,
 'tuner/trial_id': '0015'}

In [35]:
# Compare the performance to the second-best model
second_model = tuner.get_best_models(2)[1]
model_loss, model_accuracy = second_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 650us/step - accuracy: 0.7317 - loss: 0.5553
Loss: 0.555250346660614, Accuracy: 0.7316617965698242

In [19]:
# # Get the best model
# best_model = tuner.get_best_models(num_models=1)[0]

# # Get the best hyperparameters
# best_hps = tuner.get_best_hyperparameters(1)[0]

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:576: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [20]:
# # Print the best hyperparameters
# print("Best hyperparameters:")
# print(f"Activation: {best_hps.get('activation')}")
# print(f"First layer units: {best_hps.get('first_units')}")
# print(f"Number of hidden layers: {best_hps.get('num_layers')}")
# for i in range(best_hps.get('num_layers')):
#     print(f"Units in hidden layer {i+1}: {best_hps.get(f'units_{i}')}")

# # Evaluate the best model
# test_loss, test_accuracy = best_model.evaluate(X_test_scaled, y_test)
# print(f"Test accuracy: {test_accuracy:.4f}")
# print(f"Test loss: {test_loss:.4f}")

Best hyperparameters:
Activation: tanh
First layer units: 16
Number of hidden layers: 4
Units in hidden layer 1: 11
Units in hidden layer 2: 1
Units in hidden layer 3: 26
Units in hidden layer 4: 1
268/268 ━━━━━━━━━━━━━━━━━━━━ 0s 328us/step - accuracy: 0.7332 - loss: 0.5589
Test accuracy: 0.7334
Test loss: 0.5617

In [29]:
# Clear Keras session
tf.keras.backend.clear_session()