## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import keras_tuner as kt

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df['STATUS'].value_counts()

STATUS
1    34294
0        5
Name: count, dtype: int64

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME', 'STATUS'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_count = application_df['APPLICATION_TYPE'].value_counts()
application_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_count[application_count < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count[classification_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_count[classification_count < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,5000,1,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,108590,1,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,5000,0,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
3,6692,1,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,142590,1,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,0,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,5000,0,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,5000,0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,5000,1,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,36500179,0,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [11]:
# Split our preprocessed data into our features and target arrays
X = dummies_df.drop('IS_SUCCESSFUL', axis=1)
y = dummies_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Optimization Attempt #1 - Add third hidden layer and increase neurons on all three layers

In [21]:
# Define the model - deep neural net
nn = tf.keras.models.Sequential()
input_dim = len(X.columns)

# First hidden layer
nn.add(tf.keras.layers.Dense(units=120, activation="relu", input_dim=input_dim))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 120)            │         5,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 80)             │         9,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,301 (67.58 KB)

 Trainable params: 17,301 (67.58 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 469us/step - accuracy: 0.7116 - loss: 0.5855
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.7239 - loss: 0.5569
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - accuracy: 0.7305 - loss: 0.5532
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.7363 - loss: 0.5448
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.7341 - loss: 0.5447
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.7324 - loss: 0.5491
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.7310 - loss: 0.5472
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7296 - loss: 0.5524
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7373 - loss: 0.5424
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7353 - loss: 0.5419
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.7314 - loss: 0.5449
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7383 - loss: 0.5412
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.7327 - loss: 0.5480
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7342 - loss: 0.5443
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.7307 - loss: 0.5467
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.7337 - loss: 0.5416
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.7408 - loss: 0.5345
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.7375 - loss: 0.5403
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7335 - loss: 0.5417
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7340 - loss: 0.5447
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7367 - loss: 0.5427
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.7381 - loss: 0.5377
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7352 - loss: 0.5385
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.7382 - loss: 0.5403
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.7319 - loss: 0.5432
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.7366 - loss: 0.5417
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.7355 - loss: 0.5397
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.7352 - loss: 0.5401
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.7350 - loss: 0.5363
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.7402 - loss: 0.5343
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.7382 - loss: 0.5384
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.7415 - loss: 0.5327
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.7409 - loss: 0.5334
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7353 - loss: 0.5386
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - accuracy: 0.7380 - loss: 0.5361
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.7392 - loss: 0.5372
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - accuracy: 0.7393 - loss: 0.5335
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - accuracy: 0.7394 - loss: 0.5364
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7427 - loss: 0.5340
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.7399 - loss: 0.5338
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - accuracy: 0.7415 - loss: 0.5349
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.7347 - loss: 0.5395
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - accuracy: 0.7410 - loss: 0.5336
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7416 - loss: 0.5323
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step - accuracy: 0.7389 - loss: 0.5368
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7379 - loss: 0.5352
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.7379 - loss: 0.5348
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7407 - loss: 0.5321
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.7351 - loss: 0.5375
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.7377 - loss: 0.5338
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7402 - loss: 0.5295
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.7417 - loss: 0.5334
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.7435 - loss: 0.5291
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7352 - loss: 0.5390
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.7459 - loss: 0.5285
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.7398 - loss: 0.5336
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.7349 - loss: 0.5388
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7446 - loss: 0.5281
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.7416 - loss: 0.5325
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.7382 - loss: 0.5339
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.7399 - loss: 0.5353
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.7443 - loss: 0.5273
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.7426 - loss: 0.5311
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7407 - loss: 0.5336
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7354 - loss: 0.5358
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.7347 - loss: 0.5364
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.7414 - loss: 0.5284
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.7479 - loss: 0.5230
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7386 - loss: 0.5329
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - accuracy: 0.7412 - loss: 0.5285
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - accuracy: 0.7391 - loss: 0.5343
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7352 - loss: 0.5319
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.7428 - loss: 0.5280
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7414 - loss: 0.5322
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.7385 - loss: 0.5356
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.7418 - loss: 0.5311
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.7395 - loss: 0.5322
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7380 - loss: 0.5340
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.7411 - loss: 0.5340
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7375 - loss: 0.5357
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.7415 - loss: 0.5322
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.7374 - loss: 0.5345
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.7403 - loss: 0.5316
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7421 - loss: 0.5293
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.7410 - loss: 0.5286
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.7429 - loss: 0.5317
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.7411 - loss: 0.5265
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.7416 - loss: 0.5306
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7388 - loss: 0.5305
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.7409 - loss: 0.5312
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.7426 - loss: 0.5308
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.7465 - loss: 0.5258
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7398 - loss: 0.5318
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - accuracy: 0.7399 - loss: 0.5312
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7395 - loss: 0.5309
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.7407 - loss: 0.5317
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.7355 - loss: 0.5337
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.7448 - loss: 0.5284
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.7390 - loss: 0.5306
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.7385 - loss: 0.5348

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 542us/step - accuracy: 0.7303 - loss: 0.5684
Loss: 0.5684105753898621, Accuracy: 0.7302623987197876

In [ ]:
# Export our model to the native Keras format as HDF5 file format is considered to be legacy
nn.save('Output/AlphabetSoupCharity_Optimization_1.keras')

# Optimization Attempt #2

# Optimization Attempt #3 - Use Keras Tuner for hyperparameter tuning to create and test different model architectures

In [ ]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu', 'tanh', 'leaky_relu', 'sigmoid'])

    # Set input to match the dataset
    input_dim = len(X.columns)

    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=30,
        step=5), activation=activation, input_dim=input_dim))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=30,
            step=5),
            activation=activation))

    nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

    # Compile the model
    nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    return nn_model

In [ ]:
# Initialize Hyperband tuner
tuner = kt.Hyperband(
    create_model,
    objective='val_accuracy',
    max_epochs=20,
    hyperband_iterations=2,
    overwrite=True
)

# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

In [ ]:
# Get top 3 model hyperparameters and print the values
top_hyper = tuner.get_best_hyperparameters(3)
for param in top_hyper:
    print(param.values)

In [ ]:
# Evaluate the top 3 models against the test dataset
top_model = tuner.get_best_models(3)
for model in top_model:
    model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
    print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Get second best model hyperparameters
second_hyper = tuner.get_best_hyperparameters(2)[1]
second_hyper.values

In [ ]:
# Compare the performance to the second-best model
second_model = tuner.get_best_models(2)[1]
model_loss, model_accuracy = second_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# # Get the best model
# best_model = tuner.get_best_models(num_models=1)[0]

# # Get the best hyperparameters
# best_hps = tuner.get_best_hyperparameters(1)[0]

In [ ]:
# # Print the best hyperparameters
# print("Best hyperparameters:")
# print(f"Activation: {best_hps.get('activation')}")
# print(f"First layer units: {best_hps.get('first_units')}")
# print(f"Number of hidden layers: {best_hps.get('num_layers')}")
# for i in range(best_hps.get('num_layers')):
#     print(f"Units in hidden layer {i+1}: {best_hps.get(f'units_{i}')}")

# # Evaluate the best model
# test_loss, test_accuracy = best_model.evaluate(X_test_scaled, y_test)
# print(f"Test accuracy: {test_accuracy:.4f}")
# print(f"Test loss: {test_loss:.4f}")

In [ ]:
# Clear Keras session
tf.keras.backend.clear_session()